# THEME:
# https://github.com/zyro/hyde-x
#
baseurl = "https://harkx.com"
languageCode = "en-us"
title = "harkx"
disqusShortname = "harkx" # Optional, enable Disqus integration
theme = "hyde-x"
paginate = 6

[author]
    name = "@harkx"

[permalinks]
    # Optional. Change the permalink format for the 'post' content type.
    # The format shown here is the same one Jekyll/Octopress uses by default.
    post = "/blog/:year/:month/:day/:title/"

[indexes]
    # Optional. Use if you want tags and lists.
    category = "categories"

#
# All parameters below here are optional and can be mixed and matched.
#
[params]
  # Changes sidebar background and link/accent colours.
  # See below for more colour options.
  # This also works: "theme-base-08 layout-reverse", or just "layout-reverse".
  theme = "theme-base-08dark"

  # Used when a given page doesn't set its own.
  defaultDescription = "harkx technology blog"
  defaultKeywords = "harkx,blog,technology,it"

  # Select a syntax highight.
  # Check the static/css/highlight directory for options.
  highlight = "sunburst"

  # Displays under the author name in the sidebar, keep it short.
  tagline = "T(ech) & T(ravel)"

  # Metadata used to drive integrations.
  googleAuthorship = "104498694078376935988"
  googleAnalytics = "UA-54333082-2"
#  gravatarHash = "4f34ba08e46042f1189ff107cd65b8fe"
#  gravatarHash = "MD5 hash of your Gravatar email address"


  # Sidebar social links, avoid enabling too many of these if possible.
  # These should be full URLs.
  github = "https://github.com/harkx"
  bitbucket= "https://bitbucket.org/harkx"
  linkedin = "http://be.linkedin.com/in/kristofhardy"
  googleplus = ""
  facebook = ""
  twitter = "https://twitter.com/harkx"
